// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package scheme

import (
	"time"
)

const TableNameAccessToken = "access_tokens"

// AccessToken mapped from table <access_tokens>
type AccessToken struct {
	ID       string    `gorm:"column:id;primaryKey" json:"id"`
	Hash     string    `gorm:"column:hash;not null" json:"hash"`
	Type     string    `gorm:"column:type;not null" json:"type"`
	Scope    string    `gorm:"column:scope;not null" json:"scope"`
	IssuedAt time.Time `gorm:"column:issued_at;not null" json:"issued_at"`
	Exp      time.Time `gorm:"column:exp;not null" json:"exp"`
	ClientID string    `gorm:"column:client_id;not null;comment:アプリケーションID" json:"client_id"` // アプリケーションID
	UserID   string    `gorm:"column:user_id;not null" json:"user_id"`
	Revoked  bool      `gorm:"column:revoked;not null" json:"revoked"`
}

// TableName AccessToken's table name
func (*AccessToken) TableName() string {
	return TableNameAccessToken
}
