// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package scheme

import (
	"time"
)

const TableNameApp = "apps"

// App mapped from table <apps>
type App struct {
	ID           string    `gorm:"column:id;primaryKey" json:"id"`
	ClientID     string    `gorm:"column:client_id;not null" json:"client_id"`
	ClientSecret string    `gorm:"column:client_secret;not null" json:"client_secret"`
	Name         string    `gorm:"column:name;not null" json:"name"`
	CreatedAt    time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	IsEnable     bool      `gorm:"column:is_enable;not null;default:1" json:"is_enable"`
}

// TableName App's table name
func (*App) TableName() string {
	return TableNameApp
}
