// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package scheme

import (
	"time"
)

const TableNameAuth = "auths"

// Auth mapped from table <auths>
type Auth struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AuthUserID string    `gorm:"column:auth_user_id;not null" json:"auth_user_id"`
	AppID      string    `gorm:"column:app_id;not null" json:"app_id"`
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	IsEnable   bool      `gorm:"column:is_enable;not null;default:1" json:"is_enable"`
}

// TableName Auth's table name
func (*Auth) TableName() string {
	return TableNameAuth
}
