// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package scheme

import (
	"time"
)

const TableNameCode = "code"

// Code mapped from table <code>
type Code struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Token     string    `gorm:"column:token;not null" json:"token"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	Exp       time.Time `gorm:"column:exp" json:"exp"`
	IsEnable  bool      `gorm:"column:is_enable;not null;default:1" json:"is_enable"`
}

// TableName Code's table name
func (*Code) TableName() string {
	return TableNameCode
}
