// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package scheme

const TableNameConsent = "consents"

// Consent mapped from table <consents>
type Consent struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Scope    string `gorm:"column:scope" json:"scope"`
	IsEnable bool   `gorm:"column:is_enable" json:"is_enable"`
}

// TableName Consent's table name
func (*Consent) TableName() string {
	return TableNameConsent
}
