// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package scheme

const TableNameDiscord = "discords"

// Discord mapped from table <discords>
type Discord struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DiscordID string `gorm:"column:discord_id;not null" json:"discord_id"`
	UserID    string `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName Discord's table name
func (*Discord) TableName() string {
	return TableNameDiscord
}
