// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package scheme

import (
	"time"
)

const TableNameIDToken = "id_tokens"

// IDToken mapped from table <id_tokens>
type IDToken struct {
	ID       string    `gorm:"column:id;primaryKey" json:"id"`
	Hash     string    `gorm:"column:hash;not null" json:"hash"`
	Type     string    `gorm:"column:type;not null" json:"type"`
	IssuedAt time.Time `gorm:"column:issued_at;not null" json:"issued_at"`
	Exp      time.Time `gorm:"column:exp;not null" json:"exp"`
	ClientID string    `gorm:"column:client_id;not null;comment:アプリケーションID" json:"client_id"` // アプリケーションID
	Aud      string    `gorm:"column:aud;not null" json:"aud"`
	Nonce    string    `gorm:"column:nonce" json:"nonce"`
	AuthTime time.Time `gorm:"column:auth_time" json:"auth_time"`
	Acr      string    `gorm:"column:acr" json:"acr"`
	Amr      string    `gorm:"column:amr" json:"amr"`
	UserID   string    `gorm:"column:user_id;not null" json:"user_id"`
	Revoked  bool      `gorm:"column:revoked;not null" json:"revoked"`
}

// TableName IDToken's table name
func (*IDToken) TableName() string {
	return TableNameIDToken
}
