// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package scheme

const TableNameOidcToken = "oidc_tokens"

// OidcToken mapped from table <oidc_tokens>
type OidcToken struct {
	ID                  int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OidcAuthorizationID int32 `gorm:"column:oidc_authorization_id;not null" json:"oidc_authorization_id"`
	AccessTokenID       int32 `gorm:"column:access_token_id;not null" json:"access_token_id"`
	RefreshTokenID      int32 `gorm:"column:refresh_token_id;not null" json:"refresh_token_id"`
	IsEnable            bool  `gorm:"column:is_enable;not null;default:1" json:"is_enable"`
}

// TableName OidcToken's table name
func (*OidcToken) TableName() string {
	return TableNameOidcToken
}
