// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package scheme

import (
	"time"
)

const TableNameOidcAuthorization = "oidc_authorizations"

// OidcAuthorization mapped from table <oidc_authorizations>
type OidcAuthorization struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AuthID    int32     `gorm:"column:auth_id;not null" json:"auth_id"`
	CodeID    int32     `gorm:"column:code_id;not null" json:"code_id"`
	ConsentID int32     `gorm:"column:consent_id;not null" json:"consent_id"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName OidcAuthorization's table name
func (*OidcAuthorization) TableName() string {
	return TableNameOidcAuthorization
}
