// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package scheme

import (
	"time"
)

const TableNameRedirectURI = "redirect_uris"

// RedirectURI mapped from table <redirect_uris>
type RedirectURI struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AppID     string    `gorm:"column:app_id;not null" json:"app_id"`
	URI       string    `gorm:"column:uri;not null" json:"uri"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName RedirectURI's table name
func (*RedirectURI) TableName() string {
	return TableNameRedirectURI
}
