// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package scheme

import (
	"time"
)

const TableNameRefreshToken = "refresh_tokens"

// RefreshToken mapped from table <refresh_tokens>
type RefreshToken struct {
	ID       string    `gorm:"column:id;primaryKey" json:"id"`
	Hash     string    `gorm:"column:hash;not null" json:"hash"`
	Type     string    `gorm:"column:type;not null" json:"type"`
	IssuedAt time.Time `gorm:"column:issued_at;not null" json:"issued_at"`
	Exp      time.Time `gorm:"column:exp;not null" json:"exp"`
	ClientID string    `gorm:"column:client_id;not null;comment:アプリケーションID" json:"client_id"` // アプリケーションID
	UserID   string    `gorm:"column:user_id;not null" json:"user_id"`
	Revoked  bool      `gorm:"column:revoked;not null" json:"revoked"`
}

// TableName RefreshToken's table name
func (*RefreshToken) TableName() string {
	return TableNameRefreshToken
}
