// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package scheme

import (
	"time"
)

const TableNameRole = "roles"

// Role ロール情報
type Role struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	CustomID    string    `gorm:"column:custom_id" json:"custom_id"`
	Permissions int32     `gorm:"column:permissions;not null" json:"permissions"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
	IsEnable    bool      `gorm:"column:is_enable;not null;default:1" json:"is_enable"`
	System      bool      `gorm:"column:system;not null" json:"system"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
