// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package scheme

import (
	"time"
)

const TableNameSession = "sessions"

// Session mapped from table <sessions>
type Session struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	IPAddress string    `gorm:"column:ip_address;not null" json:"ip_address"`
	UserAgent string    `gorm:"column:user_agent;not null" json:"user_agent"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	IsEnable  bool      `gorm:"column:is_enable;not null;default:1" json:"is_enable"`
}

// TableName Session's table name
func (*Session) TableName() string {
	return TableNameSession
}
