// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package scheme

const TableNameUserRole = "user_role"

// UserRole mapped from table <user_role>
type UserRole struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID string `gorm:"column:user_id;not null" json:"user_id"`
	RoleID string `gorm:"column:role_id;not null" json:"role_id"`
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
