// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package scheme

const TableNameUserApp = "user_app"

// UserApp mapped from table <user_app>
type UserApp struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AppID  string `gorm:"column:app_id" json:"app_id"`
	UserID string `gorm:"column:user_id" json:"user_id"`
}

// TableName UserApp's table name
func (*UserApp) TableName() string {
	return TableNameUserApp
}
