//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "access_tokens")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub hash: String,
    pub r#type: String,
    pub scope: String,
    pub issued_at: DateTimeUtc,
    pub exp: DateTimeUtc,
    pub client_id: String,
    pub user_id: String,
    pub revoked: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::token_sets::Entity")]
    TokenSets,
}

impl Related<super::token_sets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TokenSets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
