//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "apps")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub client_secret: String,
    pub name: String,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub is_enable: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auths::Entity")]
    Auths,

    #[sea_orm(has_many = "super::redirect_uris::Entity")]
    RedirectUris,

    // 中間テーブル user_app
    #[sea_orm(has_many = "super::user_app::Entity")]
    Users,
}

/* ---------- one-to-many ---------- */

impl Related<super::auths::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Auths.def()
    }
}

impl Related<super::redirect_uris::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RedirectUris.def()
    }
}

/* ---------- many-to-many ---------- */

// App -> user_app (中間テーブル)
impl Related<super::user_app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

// App -> user (many-to-many 本体)
impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_app::Relation::User.def()
    }

    fn via() -> Option<RelationDef> {
        Some(Relation::Users.def())
    }
}

impl ActiveModelBehavior for ActiveModel {}
