//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "apps")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub client_secret: String,
    pub name: String,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub is_enable: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auths::Entity")]
    Auths,
    #[sea_orm(has_many = "super::redirect_uris::Entity")]
    RedirectUris,
    #[sea_orm(has_many = "super::user_app::Entity")]
    UserApp,
}

impl Related<super::auths::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Auths.def()
    }
}

impl Related<super::redirect_uris::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RedirectUris.def()
    }
}

impl Related<super::user_app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserApp.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
