//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "auths")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub auth_user_id: String,
    pub app_id: String,
    pub created_at: Option<DateTimeUtc>,
    pub is_enable: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app::Entity",
        from = "Column::AppId",
        to = "super::app::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Apps,
    #[sea_orm(has_many = "super::oidc_authorizations::Entity")]
    OidcAuthorizations,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::AuthUserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Apps.def()
    }
}

impl Related<super::oidc_authorizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OidcAuthorizations.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
