//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "code")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub token: String,
    pub nonce: Option<String>,
    pub code_challenge: Option<String>,
    pub code_challenge_method: Option<String>,
    pub acr: Option<String>,
    pub amr: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub exp: Option<DateTimeUtc>,
    pub is_enable: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::oidc_authorizations::Entity")]
    OidcAuthorizations,
}

impl Related<super::oidc_authorizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OidcAuthorizations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
