//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "consents")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub scope: Option<String>,
    pub is_enable: Option<i8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::oidc_authorizations::Entity")]
    OidcAuthorizations,
}

impl Related<super::oidc_authorizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OidcAuthorizations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
