//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub mod prelude;

pub mod access_tokens;
pub mod app;
pub mod auths;
pub mod code;
pub mod consents;
pub mod discords;
pub mod id_tokens;
pub mod oidc_authorizations;
pub mod redirect_uris;
pub mod refresh_tokens;
pub mod role;
pub mod sessions;
pub mod token_sets;
pub mod user;
pub mod user_app;
pub mod user_role;
