//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "oidc_authorizations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub auth_id: i32,
    #[sea_orm(unique)]
    pub code_id: i32,
    pub consent_id: i32,
    pub created_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::auths::Entity",
        from = "Column::AuthId",
        to = "super::auths::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Auths,
    #[sea_orm(
        belongs_to = "super::code::Entity",
        from = "Column::CodeId",
        to = "super::code::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Code,
    #[sea_orm(
        belongs_to = "super::consents::Entity",
        from = "Column::ConsentId",
        to = "super::consents::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Consents,
    #[sea_orm(has_one = "super::token_sets::Entity")]
    TokenSets,
}

impl Related<super::auths::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Auths.def()
    }
}

impl Related<super::code::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Code.def()
    }
}

impl Related<super::consents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Consents.def()
    }
}

impl Related<super::token_sets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TokenSets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
