//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::access_tokens::Entity as AccessTokens;
pub use super::apps::Entity as Apps;
pub use super::auths::Entity as Auths;
pub use super::code::Entity as Code;
pub use super::consents::Entity as Consents;
pub use super::discords::Entity as Discords;
pub use super::id_tokens::Entity as IdTokens;
pub use super::oidc_authorizations::Entity as OidcAuthorizations;
pub use super::redirect_uris::Entity as RedirectUris;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::roles::Entity as Roles;
pub use super::sessions::Entity as Sessions;
pub use super::token_sets::Entity as TokenSets;
pub use super::user::Entity as Users;
pub use super::user_app::Entity as UserApp;
pub use super::user_role::Entity as UserRole;
