//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "token_sets")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub oidc_authorization_id: i32,
    #[sea_orm(unique)]
    pub access_token_id: String,
    #[sea_orm(unique)]
    pub refresh_token_id: String,
    #[sea_orm(unique)]
    pub id_token_id: String,
    pub is_enable: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::access_tokens::Entity",
        from = "Column::AccessTokenId",
        to = "super::access_tokens::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccessTokens,
    #[sea_orm(
        belongs_to = "super::id_tokens::Entity",
        from = "Column::IdTokenId",
        to = "super::id_tokens::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    IdTokens,
    #[sea_orm(
        belongs_to = "super::oidc_authorizations::Entity",
        from = "Column::OidcAuthorizationId",
        to = "super::oidc_authorizations::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    OidcAuthorizations,
    #[sea_orm(
        belongs_to = "super::refresh_tokens::Entity",
        from = "Column::RefreshTokenId",
        to = "super::refresh_tokens::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RefreshTokens,
}

impl Related<super::access_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessTokens.def()
    }
}

impl Related<super::id_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdTokens.def()
    }
}

impl Related<super::oidc_authorizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OidcAuthorizations.def()
    }
}

impl Related<super::refresh_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefreshTokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
