//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub custom_id: String,
    pub name: String,
    pub password_hash: Option<String>,
    #[sea_orm(unique)]
    pub email: String,
    pub external_email: String,
    pub period: Option<String>,
    pub joined_at: Option<DateTime>,
    pub is_system: Option<bool>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub is_enable: Option<bool>,
    pub is_suspended: Option<bool>,
    pub suspended_until: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub suspended_reason: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auths::Entity")]
    Auths,
    #[sea_orm(has_many = "super::discord::Entity")]
    Discords,
    #[sea_orm(has_many = "super::session::Entity")]
    Sessions,
    #[sea_orm(has_many = "super::user_app::Entity")]
    UserApp,
    #[sea_orm(has_many = "super::user_role::Entity")]
    Roles,
}

impl Related<super::auths::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Auths.def()
    }
}

impl Related<super::discord::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Discords.def()
    }
}

impl Related<super::session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::user_app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserApp.def()
    }
}

impl Related<super::user_role::Entity> for Entity {
    fn to() -> RelationDef {
        // User -> user_role (has_many)
        Relation::Roles.def()
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        // Go to Role via the join table's relation to Role
        super::user_role::Relation::Roles.def()
    }

    fn via() -> Option<RelationDef> {
        // Use this entity's relation to the join table as the via
        Some(Relation::Roles.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
