//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub custom_id: String,
    pub name: String,
    #[serde(skip_serializing)]
    pub password_hash: Option<String>,
    #[sea_orm(unique)]
    pub email: String,
    pub external_email: String,
    pub birthdate: Option<chrono::NaiveDate>,
    pub email_verified: bool,
    pub period: Option<String>,
    pub joined_at: Option<DateTime>,
    pub is_system: Option<bool>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub is_enable: Option<bool>,
    pub is_suspended: Option<bool>,
    pub suspended_until: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub suspended_reason: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auths::Entity")]
    Auths,
    #[sea_orm(has_many = "super::discord::Entity")]
    Discords,
    #[sea_orm(has_many = "super::session::Entity")]
    Sessions,
    #[sea_orm(has_many = "super::user_app::Entity")]
    UserApp,
    #[sea_orm(has_many = "super::user_role::Entity")]
    Roles,
    #[sea_orm(has_many = "super::email_verification::Entity")]
    EmailVerifications,
}

impl Related<super::auths::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Auths.def()
    }
}

impl Related<super::discord::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Discords.def()
    }
}

impl Related<super::session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::user_app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserApp.def()
    }
}

impl Related<super::user_role::Entity> for Entity {
    fn to() -> RelationDef {
        // User -> user_role (has_many)
        Relation::Roles.def()
    }
}

impl Related<super::role::Entity> for Entity {
    // The final relation is User -> user_role -> Role
    fn to() -> RelationDef {
        super::user_role::Relation::Role.def()
    }

    fn via() -> Option<RelationDef> {
        // The original relation is CakeFilling -> Cake,
        // after `rev` it becomes Cake -> CakeFilling
        Some(super::user_role::Relation::Role.def().rev())
    }
}

impl Related<super::email_verification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmailVerifications.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
