// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/health": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "死活監視用",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_controller_system.Response"
                        }
                    }
                }
            }
        },
        "/v1/users": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "ユーザー一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_controller_users.UsersResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/:id": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "ユーザーの詳細情報を取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ユーザーID",
                        "name": "request",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_controller_users.UserResponseModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api_internal_controller_system.Response": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "api_internal_controller_users.UserResponseModel": {
            "type": "object",
            "properties": {
                "custom_id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "external_email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_enable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "period": {
                    "type": "string"
                }
            }
        },
        "api_internal_controller_users.UsersResponse": {
            "type": "object",
            "properties": {
                "pages": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api_internal_controller_users.UserResponseModel"
                    }
                }
            }
        },
        "github.com_UniPro-tech_UniQUE-API_api_internal_controller_system.Response": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "github.com_UniPro-tech_UniQUE-API_api_internal_controller_users.UserResponseModel": {
            "type": "object",
            "properties": {
                "custom_id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "external_email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_enable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "period": {
                    "type": "string"
                }
            }
        },
        "github.com_UniPro-tech_UniQUE-API_api_internal_controller_users.UsersResponse": {
            "type": "object",
            "properties": {
                "pages": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_users.UserResponseModel"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v0.1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "ユーザー管理サービスAPI",
	Description:      "ユーザー管理サービスAPIの機能",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
